- name: Fix JVM target
  working-directory: project/RajjoAI_Android_Project
  run: |
    sed -i '/android {/a\
        compileOptions {\
            sourceCompatibility JavaVersion.VERSION_17\
            targetCompatibility JavaVersion.VERSION_17\
        }\
    ' app/build.gradle

- name: Build APK
  working-directory: project/RajjoAI_Android_Project
  run: gradle assembleDebug
